# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyBirdApp', '0003_post_id_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.TextField(default='default.jpg', max_length=500),
        ),
    ]
