# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PyBirdApp', '0004_profile_avatar'),
        ('PyBirdApp', '0005_auto_20170710_2108'),
    ]

    operations = [
    ]
