# Generated by Django 2.1.2 on 2018-10-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyBirdApp', '0006_merge_20170712_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
            ],
        ),
    ]
