# Generated by Django 2.1.2 on 2018-10-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PyBirdApp', '0007_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='playerClass',
            field=models.TextField(default='NaN', max_length=50),
        ),
    ]
